services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - path: .env
        required: false

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - BACKEND_API_URL=http://backend:80/api
